spring.application.name=activity-tracker

server.port=8080

# H2 Database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Caricamento dati iniziali
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true


#spring.sql.init.mode=always
#spring.jpa.hibernate.ddl-auto=create-drop
# H2 Database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver

# Definisci esplicitamente il path (fondamentale in Boot 4)
spring.h2.console.path=/h2-console
